### Сегодня мы познакомимся с матрицами

###### Матрица  - это таблица разделенная на стобцы и строки. 

Обычно еще размер записывается как NxM, где N - число строк, M - число столбцов

Вот так она выглядит
![matrix](http://cs4.pikabu.ru/images/big_size_comm/2014-12_4/14189417864136.png)

Конечно, можно сделать ее большой и страшной. Вот такой например:
![matrix](http://rfpro.ru/php/formula.php?id=23558)

In [7]:
# Покажу как создавать матрицу в python'e
# Для начала возьмем полезную библиотеку для работы с матрицами
import numpy as np
# Можно заполнить матрицу сразу своими числами
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
# Можно использовать заранее подготовленные матрицы
# Не забывайте указывать размеры матрицы.
np.ones((3,3)) # Создаст матрицу 3x3, заполненную единицами (типа float)

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [19]:
np.zeros((5,4)) # Создаст матрицу 5x4 заполненную нулями (Тоже дробного типа)

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [21]:
# Теперь пройдем по всем значениям matrix
for line in matrix:
    for element in line:
        print(element, end=' ')

1 2 3 4 5 6 7 8 9 

In [28]:
# Ну и всегда можно вытащить и изменить элемент, если мы знаем его индексы.
# Помните, что индексация всегда начинается с нуля
matrix[2][1] = 10
print(matrix)

[[ 1  2  3]
 [ 4  5  6]
 [ 7 10  9]]


Теперь перейдем к нашим любимым геномам

Пускай у нас есть M штук ДНК строк, в каждой из которых N штук символов. Логично записать это все в матрицу. Тогда получим матрицу размера NxM, где в каждом столбце находится цепочка ДНК.

#### Задача 1. 
Необходимо посчитать число вхождениий символов 'A', 'C', 'G', 'T' в каждую ДНК и записать их в матрицу профиля. В матрице ответа 4 строки, по одной для каждой буквы. То есть выглядит вот так
![answer](http://www.imageup.ru/img77/2484361/line.png?nc)

#### Входные данные:
M строк ДНК длины N

#### Вывод:
Матрица профиля для этих строк


#### Задача 2.

Чтобы было проще давайте сделаем лист самых частых символов в строке. То есть лист, где на i-том месте будет стоять символ, у которого самое большое значение в i-том столбце матрицы профиля. Назовем его лист решений.
![profile](http://www.imageup.ru/img77/2484385/dnk.png?nc)

#### Входные данные: 
Те же

#### Вывод:
Лист решений
